In [20]:
import networkx as nx
import numpy as np

In [10]:
# build a graph
g = nx.Graph()
x = [0,1,1,1,1,1,1,1,3,4,4,4,4,4,4]
y = [3,2,3,4,5,6,7,8,4,5,6,7,8,9,10]
g.add_edges_from(zip(x,y))
nx.degree(g)

{0: 1, 1: 7, 2: 1, 3: 3, 4: 8, 5: 2, 6: 2, 7: 2, 8: 2, 9: 1, 10: 1}

In [29]:
A = np.matrix([[0,0,0,1,0,0,0,0,0,0,0], 
              [0,0,1,1,1,1,1,1,1,0,0],
              [0,1,0,0,0,0,0,0,0,0,0],
              [1,1,0,0,1,0,0,0,0,0,0],
              [0,1,0,1,0,1,1,1,1,1,1],
              [0,1,0,0,1,0,0,0,0,0,0],
              [0,1,0,0,1,0,0,0,0,0,0],
              [0,1,0,0,1,0,0,0,0,0,0],
              [0,1,0,0,1,0,0,0,0,0,0],
              [0,0,0,0,1,0,0,0,0,0,0],
              [0,1,0,0,0,0,0,0,0,0,0]])

In [44]:
x1 = [1,0,0,4,0,1,0,2,0,3,0]
x1 = x1*A
print (x1)
print (x1.sum())
(x1/x1.sum())*11
#len(A)

[[ 4  7  0  1 10  0  0  0  0  0  0]]
22


matrix([[ 2. ,  3.5,  0. ,  0.5,  5. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ]])

In [99]:
def get_eigenvector_centrality(A):
    n = len(A)
    x0 = np.array([0]*n)
    #x1 = np.array([1,0,0,4,0,1,0,2,0,3,0])
    x1 = np.array([1,1,2,5,0,0,0,0,0,0,0])
    eps = 1/10**6
    iter = 0;
    while ((np.absolute((x0 - x1)).sum()) > eps):
        x0 = x1
        x1 = x1*A
        x1 = (x1/x1.sum())*n
        iter += 1
    return x1    

In [100]:
res = get_eigenvector_centrality(A)
res

matrix([[ 0.27654966,  2.06763837,  0.52399872,  1.09123319,  1.96169198,
          1.02114759,  1.02114759,  1.02114759,  1.02114759,  0.49714887,
          0.49714887]])

In [ ]:
# Eigenvector centrality (direct method)
#INPUT
# g = graph
# t = precision
# OUTPUT
# A list with:
# vector = centrality vector
# value = eigenvalue
# iter = number of iterations

eigenvector.centrality = function(g, t) {
  A = get.adjacency(g);
  n = vcount(g);
  x0 = rep(0, n);
  x1 = rep(1/n, n);
  eps = 1/10^t;
  iter = 0;
  while (sum(abs(x0 - x1)) > eps) {
    x0 = x1;
    x1 = as.vector(x1 %*% A);
    m = x1[which.max(abs(x1))];
    x1 = x1 / m;
    iter = iter + 1;
  } 
  return(list(vector = x1, value = m, iter = iter))
}